backend:
  name: git-gateway
  branch: main # or whatever your main branch is called
  # Add the following line to use Auth0 as the external authentication provider
  auth_provider: auth0

media_folder: "images/uploads" # Where to store uploaded images
public_folder: "/images/uploads" # The path to the folder from the root of the site

collections:
  - name: "news"
    label: "News Aarticles"
    folder: "_posts" # The folder where the news markdown files will be stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename format
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}